
version: '3.1'
services:
  wise-demo:
    environment:
      - CONTAINER_NAME=${CONTAINER_NAME}
      - HOST_JOBS_FOLDER=${HOST_JOBS_FOLDER}
    build:
      context: .
      args:
        HOST_JOBS_FOLDER: $HOST_JOBS_FOLDER
      dockerfile: wise.Dockerfile
    image: wise_demo_latest
    container_name: ${CONTAINER_NAME}   
    ports:
      - ${EXTERNAL_PORT}:3000
    volumes:
    - ${HOST_DATA_FOLDER}:/root/app_data