
version: '3.1'
services:
  wise-demo:
    build:
      context: .
      dockerfile: wise.Dockerfile
    container_name: WISE-DEMO-DEVELOPER
    restart: "unless-stopped"
    ports:
      - 3932:3000
    volumes:
    - /home/sparcsadmin/wise_demo_data/:/app_data