
version: '3.1'
services:
  wise-demo:
    build:
      context: .
      dockerfile: wise.Dockerfile
    container_name: ${CONTAINER_NAME}   
    ports:
      - ${EXTERNAL_PORT}:3000
    volumes:
    - ${HOST_DATA_FOLDER}:/root/app_data